name: Release

on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pnpm-setup
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm ci:release
          skip-publish-pr: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Get Version from Changesets
        id: get_version
        run: echo "RELEASE_VERSION=$(cat .changeset/releases/latest.yml | grep 'version:' | awk '{print $2}')" >> $GITHUB_ENV
      - name: Tag the release
        run: |
          git tag "v${{ env.RELEASE_VERSION }}"
          git push origin "v${{ env.RELEASE_VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
